deployer:
    build: .
    environment:
        TF_LOG: "debug"
    links:
        - mysql
        - etcd
    volumes:
        - "./inputs:/usr/local/deployer/inputs:ro"
    restart: on-failure
mysql:
    image: mariadb:10.1
    environment:
        MYSQL_ROOT_PASSWORD: example
    volumes:
        - "/var/lib/mysql"
    ports:
        - "3306:3306"
etcd:
    image: appcelerator/etcd:3.2.9
    volumes:
        - "/data"
    ports:
        - "2379:2379"
