deployer1:
    build: .
    links:
        - mysql
        - etcd
    volumes:
        - "./inputs:/usr/local/deployer/inputs:ro"
    restart: on-failure
deployer2:
    build: .
    links:
        - mysql
        - etcd
    volumes:
        - "./inputs:/usr/local/deployer/inputs:ro"
    restart: on-failure
mysql:
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: example
    volumes:
        - "./tmp/mysql:/var/lib/mysql"
    ports:
        - "3306:3306"
etcd:
    image: appcelerator/etcd:3.2.9
    volumes:
        - "./tmp/etcd:/data"
    ports:
        - "2379:2379"
